# Generated by Django 3.2.15 on 2022-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1234, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
